//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once
//+
// Provider CCTTSMS Event Count 1
//+
EXTERN_C __declspec(selectany) const GUID CCTTSMS_EVENTS = {0x2cd11903, 0x526e, 0x441d, {0x96, 0x39, 0x81, 0xec, 0xd9, 0xf7, 0xfe, 0x9b}};

//
// Channel
//
#define CCTTSMS_EVENTS_CHANNEL_C1 0x8
#define CCTTSMS_Application 0x10
#define CCTTSMS_Security 0x11
#define CCTTSMS_Setup 0x12
#define CCTTSMS_System 0x13

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR DUMMY_EVENT = {0x64, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0};
#define DUMMY_EVENT_value 0x64
//+
// Provider CCTTSQLX3 Event Count 1
//+
EXTERN_C __declspec(selectany) const GUID CCTTSQLX3_EVENTS = {0x50c62a8e, 0x3255, 0x4ae5, {0xbf, 0xb1, 0xa4, 0x87, 0x84, 0x6a, 0x14, 0x42}};

//
// Channel
//
#define CCTTSQLX3_EVENTS_CHANNEL_C2 0x8
#define CCTTSQLX3_Applications 0x10
#define CCTTSQLX3_Security 0x11
#define CCTTSQLX3_Setup 0x12
#define CCTTSQLX3_System 0x13

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR DUMMY_EVENT = {0x64, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0};
#define DUMMY_EVENT_value 0x64
#define MSG_channel_System                   0x90000001L
#define MSG_Custom_Forwarded_Events_event_100_message 0xB0000064L
